package languages

import (
	"github.com/turenlabs/batou-rules/rules"
	"github.com/turenlabs/batou-core/taint"
)

func (javaCatalog) Sinks() []taint.SinkDef {
	return []taint.SinkDef{
		// SQL injection
		{ID: "java.sql.statement.execute", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `(?:Statement|stmt)\.execute\s*\(`, ObjectType: "Statement", MethodName: "execute", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "SQL Statement.execute with potential injection", CWEID: "CWE-89", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.sql.statement.executequery", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `(?:Statement|stmt)\.executeQuery\s*\(`, ObjectType: "Statement", MethodName: "executeQuery", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "SQL Statement.executeQuery with potential injection", CWEID: "CWE-89", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.sql.statement.executeupdate", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `(?:Statement|stmt)\.executeUpdate\s*\(`, ObjectType: "Statement", MethodName: "executeUpdate", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "SQL Statement.executeUpdate with potential injection", CWEID: "CWE-89", OWASPCategory: "A03:2021-Injection"},

		// Command injection
		{ID: "java.runtime.exec", Category: taint.SnkCommand, Language: rules.LangJava, Pattern: `Runtime\.(?:getRuntime\s*\(\s*\)\s*\.)?exec\s*\(`, ObjectType: "Runtime", MethodName: "exec", DangerousArgs: []int{-1}, Severity: rules.Critical, Description: "OS command execution via Runtime.exec", CWEID: "CWE-78", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.processbuilder", Category: taint.SnkCommand, Language: rules.LangJava, Pattern: `new\s+ProcessBuilder\s*\(`, ObjectType: "ProcessBuilder", MethodName: "ProcessBuilder", DangerousArgs: []int{-1}, Severity: rules.Critical, Description: "OS command execution via ProcessBuilder", CWEID: "CWE-78", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.processbuilder.command", Category: taint.SnkCommand, Language: rules.LangJava, Pattern: `(?:ProcessBuilder|pb)\.command\s*\(`, ObjectType: "ProcessBuilder", MethodName: "command", DangerousArgs: []int{-1}, Severity: rules.Critical, Description: "OS command execution via ProcessBuilder.command()", CWEID: "CWE-78", OWASPCategory: "A03:2021-Injection"},

		// XSS
		{ID: "java.servlet.writer.write", Category: taint.SnkHTMLOutput, Language: rules.LangJava, Pattern: `response\.getWriter\s*\(\s*\)\s*\.write\s*\(`, ObjectType: "PrintWriter", MethodName: "write", DangerousArgs: []int{0}, Severity: rules.High, Description: "HTTP response write (XSS)", CWEID: "CWE-79", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.servlet.writer.println", Category: taint.SnkHTMLOutput, Language: rules.LangJava, Pattern: `response\.getWriter\s*\(\s*\)\s*\.println\s*\(`, ObjectType: "PrintWriter", MethodName: "println", DangerousArgs: []int{0}, Severity: rules.High, Description: "HTTP response println (XSS)", CWEID: "CWE-79", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.out.println.html", Category: taint.SnkHTMLOutput, Language: rules.LangJava, Pattern: `out\.print(?:ln)?\s*\(\s*["']<`, ObjectType: "PrintWriter", MethodName: "out.println (HTML)", DangerousArgs: []int{0}, Severity: rules.High, Description: "Direct HTML construction via out.println with string concatenation (XSS)", CWEID: "CWE-79", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.writer.println.html", Category: taint.SnkHTMLOutput, Language: rules.LangJava, Pattern: `writer\.print(?:ln)?\s*\(\s*["']<`, ObjectType: "PrintWriter", MethodName: "writer.println (HTML)", DangerousArgs: []int{0}, Severity: rules.High, Description: "Direct HTML construction via writer.println with string concatenation (XSS)", CWEID: "CWE-79", OWASPCategory: "A03:2021-Injection"},

		// Redirect
		{ID: "java.servlet.forward", Category: taint.SnkRedirect, Language: rules.LangJava, Pattern: `(?:RequestDispatcher|dispatcher)\.forward\s*\(`, ObjectType: "RequestDispatcher", MethodName: "forward", DangerousArgs: []int{0}, Severity: rules.High, Description: "Request dispatch forward", CWEID: "CWE-601", OWASPCategory: "A01:2021-Broken Access Control"},
		{ID: "java.servlet.sendredirect", Category: taint.SnkRedirect, Language: rules.LangJava, Pattern: `response\.sendRedirect\s*\(`, ObjectType: "HttpServletResponse", MethodName: "sendRedirect", DangerousArgs: []int{0}, Severity: rules.High, Description: "HTTP redirect with user-controlled URL", CWEID: "CWE-601", OWASPCategory: "A01:2021-Broken Access Control"},

		// Request dispatcher with tainted path
		{ID: "java.servlet.getrequestdispatcher", Category: taint.SnkRedirect, Language: rules.LangJava, Pattern: `\.getRequestDispatcher\s*\(`, ObjectType: "ServletRequest", MethodName: "getRequestDispatcher", DangerousArgs: []int{0}, Severity: rules.High, Description: "Request dispatcher with user-controlled path (path traversal)", CWEID: "CWE-22", OWASPCategory: "A01:2021-Broken Access Control"},

		// File operations
		{ID: "java.file.new", Category: taint.SnkFileWrite, Language: rules.LangJava, Pattern: `new\s+File\s*\(`, ObjectType: "File", MethodName: "File", DangerousArgs: []int{0}, Severity: rules.High, Description: "File path with potential traversal", CWEID: "CWE-22", OWASPCategory: "A01:2021-Broken Access Control"},
		{ID: "java.fileoutputstream", Category: taint.SnkFileWrite, Language: rules.LangJava, Pattern: `new\s+FileOutputStream\s*\(`, ObjectType: "FileOutputStream", MethodName: "FileOutputStream", DangerousArgs: []int{0}, Severity: rules.High, Description: "FileOutputStream with potential path traversal", CWEID: "CWE-22", OWASPCategory: "A01:2021-Broken Access Control"},
		{ID: "java.filewriter", Category: taint.SnkFileWrite, Language: rules.LangJava, Pattern: `new\s+FileWriter\s*\(`, ObjectType: "FileWriter", MethodName: "FileWriter", DangerousArgs: []int{0}, Severity: rules.High, Description: "FileWriter with potential path traversal", CWEID: "CWE-22", OWASPCategory: "A01:2021-Broken Access Control"},

		// SSRF
		{ID: "java.url.new", Category: taint.SnkURLFetch, Language: rules.LangJava, Pattern: `new\s+URL\s*\(`, ObjectType: "URL", MethodName: "URL", DangerousArgs: []int{0}, Severity: rules.High, Description: "URL with user-controlled address (SSRF)", CWEID: "CWE-918", OWASPCategory: "A10:2021-Server-Side Request Forgery"},
		{ID: "java.httpurlconnection", Category: taint.SnkURLFetch, Language: rules.LangJava, Pattern: `HttpURLConnection`, ObjectType: "HttpURLConnection", MethodName: "HttpURLConnection", DangerousArgs: []int{0}, Severity: rules.High, Description: "HTTP connection with potential SSRF", CWEID: "CWE-918", OWASPCategory: "A10:2021-Server-Side Request Forgery"},
		{ID: "java.spring.resttemplate", Category: taint.SnkURLFetch, Language: rules.LangJava, Pattern: `(?:RestTemplate|restTemplate)\.getForObject\s*\(`, ObjectType: "RestTemplate", MethodName: "getForObject", DangerousArgs: []int{0}, Severity: rules.High, Description: "Spring RestTemplate SSRF", CWEID: "CWE-918", OWASPCategory: "A10:2021-Server-Side Request Forgery"},

		// Deserialization
		{ID: "java.objectinputstream.readobject", Category: taint.SnkDeserialize, Language: rules.LangJava, Pattern: `ObjectInputStream.*\.readObject\s*\(`, ObjectType: "ObjectInputStream", MethodName: "readObject", DangerousArgs: []int{-1}, Severity: rules.Critical, Description: "Unsafe Java deserialization", CWEID: "CWE-502", OWASPCategory: "A08:2021-Software and Data Integrity Failures"},
		{ID: "java.xmldecoder.readobject", Category: taint.SnkDeserialize, Language: rules.LangJava, Pattern: `XMLDecoder.*\.readObject\s*\(`, ObjectType: "XMLDecoder", MethodName: "readObject", DangerousArgs: []int{-1}, Severity: rules.Critical, Description: "Unsafe XML deserialization", CWEID: "CWE-502", OWASPCategory: "A08:2021-Software and Data Integrity Failures"},

		// XXE
		{ID: "java.xml.documentbuilder.parse", Category: taint.SnkXPath, Language: rules.LangJava, Pattern: `DocumentBuilder.*\.parse\s*\(`, ObjectType: "DocumentBuilder", MethodName: "parse", DangerousArgs: []int{0}, Severity: rules.High, Description: "XML parsing (potential XXE)", CWEID: "CWE-611", OWASPCategory: "A05:2021-Security Misconfiguration"},
		{ID: "java.xml.saxparser.parse", Category: taint.SnkXPath, Language: rules.LangJava, Pattern: `SAXParser.*\.parse\s*\(`, ObjectType: "SAXParser", MethodName: "parse", DangerousArgs: []int{0}, Severity: rules.High, Description: "SAX XML parsing (potential XXE)", CWEID: "CWE-611", OWASPCategory: "A05:2021-Security Misconfiguration"},

		// Code evaluation
		{ID: "java.scriptengine.eval", Category: taint.SnkEval, Language: rules.LangJava, Pattern: `ScriptEngine.*\.eval\s*\(`, ObjectType: "ScriptEngine", MethodName: "eval", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "Script engine code evaluation", CWEID: "CWE-94", OWASPCategory: "A03:2021-Injection"},

		// LDAP
		{ID: "java.ldap.dircontext.search", Category: taint.SnkLDAP, Language: rules.LangJava, Pattern: `DirContext.*\.search\s*\(`, ObjectType: "DirContext", MethodName: "search", DangerousArgs: []int{1}, Severity: rules.High, Description: "LDAP query injection", CWEID: "CWE-90", OWASPCategory: "A03:2021-Injection"},

		// Log injection (CWE-117)
		{ID: "java.logger.info", Category: taint.SnkLog, Language: rules.LangJava, Pattern: `(?:logger|Logger|LOG|log)\.info\s*\(`, ObjectType: "Logger", MethodName: "info", DangerousArgs: []int{0}, Severity: rules.Medium, Description: "Log injection via Logger.info", CWEID: "CWE-117", OWASPCategory: "A09:2021-Security Logging and Monitoring Failures"},
		{ID: "java.logger.debug", Category: taint.SnkLog, Language: rules.LangJava, Pattern: `(?:logger|Logger|LOG|log)\.debug\s*\(`, ObjectType: "Logger", MethodName: "debug", DangerousArgs: []int{0}, Severity: rules.Medium, Description: "Log injection via Logger.debug", CWEID: "CWE-117", OWASPCategory: "A09:2021-Security Logging and Monitoring Failures"},
		{ID: "java.logger.warn", Category: taint.SnkLog, Language: rules.LangJava, Pattern: `(?:logger|Logger|LOG|log)\.warn\s*\(`, ObjectType: "Logger", MethodName: "warn", DangerousArgs: []int{0}, Severity: rules.Medium, Description: "Log injection via Logger.warn", CWEID: "CWE-117", OWASPCategory: "A09:2021-Security Logging and Monitoring Failures"},
		{ID: "java.logger.error", Category: taint.SnkLog, Language: rules.LangJava, Pattern: `(?:logger|Logger|LOG|log)\.error\s*\(`, ObjectType: "Logger", MethodName: "error", DangerousArgs: []int{0}, Severity: rules.Medium, Description: "Log injection via Logger.error", CWEID: "CWE-117", OWASPCategory: "A09:2021-Security Logging and Monitoring Failures"},
		{ID: "java.logger.trace", Category: taint.SnkLog, Language: rules.LangJava, Pattern: `(?:logger|Logger|LOG|log)\.trace\s*\(`, ObjectType: "Logger", MethodName: "trace", DangerousArgs: []int{0}, Severity: rules.Medium, Description: "Log injection via Logger.trace", CWEID: "CWE-117", OWASPCategory: "A09:2021-Security Logging and Monitoring Failures"},
		{ID: "java.system.out.println", Category: taint.SnkLog, Language: rules.LangJava, Pattern: `System\.out\.println\s*\(`, ObjectType: "System.out", MethodName: "println", DangerousArgs: []int{0}, Severity: rules.Medium, Description: "System.out.println with potentially tainted data (log injection)", CWEID: "CWE-117", OWASPCategory: "A09:2021-Security Logging and Monitoring Failures"},
		{ID: "java.system.err.println", Category: taint.SnkLog, Language: rules.LangJava, Pattern: `System\.err\.println\s*\(`, ObjectType: "System.err", MethodName: "println", DangerousArgs: []int{0}, Severity: rules.Medium, Description: "System.err.println with potentially tainted data (log injection)", CWEID: "CWE-117", OWASPCategory: "A09:2021-Security Logging and Monitoring Failures"},

		// Hibernate HQL injection
		{ID: "java.hibernate.createquery", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `(?:Session|session|entityManager)\.createQuery\s*\(`, ObjectType: "Session", MethodName: "createQuery", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "Hibernate createQuery with potential HQL injection via string concatenation", CWEID: "CWE-89", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.hibernate.createnativequery", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `(?:Session|session|entityManager)\.createNativeQuery\s*\(`, ObjectType: "Session", MethodName: "createNativeQuery", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "Hibernate createNativeQuery with potential SQL injection", CWEID: "CWE-89", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.hibernate.createsqlquery", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `(?:Session|session)\.createSQLQuery\s*\(`, ObjectType: "Session", MethodName: "createSQLQuery", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "Hibernate createSQLQuery with potential SQL injection", CWEID: "CWE-89", OWASPCategory: "A03:2021-Injection"},

		// MyBatis ${} interpolation
		{ID: "java.mybatis.interpolation", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `\$\{[^}]+\}`, ObjectType: "MyBatis", MethodName: "${}", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "MyBatis ${} string interpolation in SQL (use #{} for parameterized queries)", CWEID: "CWE-89", OWASPCategory: "A03:2021-Injection"},

		// Thymeleaf template injection
		{ID: "java.thymeleaf.utext", Category: taint.SnkHTMLOutput, Language: rules.LangJava, Pattern: `th:utext`, ObjectType: "Thymeleaf", MethodName: "th:utext", DangerousArgs: []int{0}, Severity: rules.High, Description: "Thymeleaf th:utext renders unescaped HTML (XSS)", CWEID: "CWE-79", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.thymeleaf.attr.injection", Category: taint.SnkHTMLOutput, Language: rules.LangJava, Pattern: `th:attr`, ObjectType: "Thymeleaf", MethodName: "th:attr", DangerousArgs: []int{0}, Severity: rules.High, Description: "Thymeleaf th:attr with user-controlled attribute value", CWEID: "CWE-79", OWASPCategory: "A03:2021-Injection"},

		// JSP scriptlet injection
		{ID: "java.jsp.scriptlet", Category: taint.SnkHTMLOutput, Language: rules.LangJava, Pattern: `<%=\s*[^%]*%>`, ObjectType: "JSP", MethodName: "<%=%>", DangerousArgs: []int{0}, Severity: rules.High, Description: "JSP expression tag outputs unescaped data (XSS)", CWEID: "CWE-79", OWASPCategory: "A03:2021-Injection"},

		// JNDI lookup (log4shell style)
		{ID: "java.jndi.initialcontext.lookup", Category: taint.SnkEval, Language: rules.LangJava, Pattern: `(?:InitialContext|ctx|context)\.lookup\s*\(`, ObjectType: "InitialContext", MethodName: "lookup", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "JNDI lookup with user-controlled input (log4shell/RCE)", CWEID: "CWE-917", OWASPCategory: "A03:2021-Injection"},

		// Reflection-based code execution
		{ID: "java.reflection.class.forname", Category: taint.SnkEval, Language: rules.LangJava, Pattern: `Class\.forName\s*\(`, ObjectType: "Class", MethodName: "forName", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "Reflection Class.forName with user-controlled class name", CWEID: "CWE-470", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.reflection.method.invoke", Category: taint.SnkEval, Language: rules.LangJava, Pattern: `(?:Method|method)\.invoke\s*\(`, ObjectType: "Method", MethodName: "invoke", DangerousArgs: []int{-1}, Severity: rules.Critical, Description: "Reflection Method.invoke with tainted arguments", CWEID: "CWE-470", OWASPCategory: "A03:2021-Injection"},

		// ReDoS via Pattern.compile
		{ID: "java.regex.pattern.compile", Category: taint.SnkEval, Language: rules.LangJava, Pattern: `Pattern\.compile\s*\(`, ObjectType: "Pattern", MethodName: "compile", DangerousArgs: []int{0}, Severity: rules.High, Description: "Pattern.compile with user-controlled regex (ReDoS)", CWEID: "CWE-1333", OWASPCategory: "A03:2021-Injection"},

		// Weak cryptography
		{ID: "java.crypto.cipher.getinstance", Category: taint.SnkCrypto, Language: rules.LangJava, Pattern: `Cipher\.getInstance\s*\(`, ObjectType: "Cipher", MethodName: "getInstance", DangerousArgs: []int{0}, Severity: rules.High, Description: "Cipher.getInstance with potentially weak algorithm (DES/ECB)", CWEID: "CWE-327", OWASPCategory: "A02:2021-Cryptographic Failures"},
		{ID: "java.crypto.messagedigest.md5", Category: taint.SnkCrypto, Language: rules.LangJava, Pattern: `MessageDigest\.getInstance\s*\(\s*["']MD5["']`, ObjectType: "MessageDigest", MethodName: "getInstance(MD5)", DangerousArgs: []int{0}, Severity: rules.Medium, Description: "Weak MD5 hash algorithm usage", CWEID: "CWE-328", OWASPCategory: "A02:2021-Cryptographic Failures"},
		{ID: "java.crypto.messagedigest.sha1", Category: taint.SnkCrypto, Language: rules.LangJava, Pattern: `MessageDigest\.getInstance\s*\(\s*["']SHA-?1["']`, ObjectType: "MessageDigest", MethodName: "getInstance(SHA1)", DangerousArgs: []int{0}, Severity: rules.Medium, Description: "Weak SHA-1 hash algorithm usage", CWEID: "CWE-328", OWASPCategory: "A02:2021-Cryptographic Failures"},
		{ID: "java.crypto.insecure_random", Category: taint.SnkCrypto, Language: rules.LangJava, Pattern: `new\s+Random\s*\(|Math\.random\s*\(`, ObjectType: "Random", MethodName: "Random/Math.random", DangerousArgs: []int{-1}, Severity: rules.High, Description: "java.util.Random used for security (use SecureRandom instead)", CWEID: "CWE-338", OWASPCategory: "A02:2021-Cryptographic Failures"},
		{ID: "java.crypto.ecb_mode", Category: taint.SnkCrypto, Language: rules.LangJava, Pattern: `Cipher\.getInstance\s*\(\s*["'](?:DES|AES)/ECB`, ObjectType: "Cipher", MethodName: "getInstance(ECB)", DangerousArgs: []int{0}, Severity: rules.High, Description: "ECB mode cipher usage (no diffusion, use CBC/GCM)", CWEID: "CWE-327", OWASPCategory: "A02:2021-Cryptographic Failures"},

		// Jackson unsafe deserialization config
		{ID: "java.jackson.enabledefaulttyping", Category: taint.SnkDeserialize, Language: rules.LangJava, Pattern: `(?:ObjectMapper|objectMapper|mapper)\.enableDefaultTyping\s*\(`, ObjectType: "ObjectMapper", MethodName: "enableDefaultTyping", DangerousArgs: []int{-1}, Severity: rules.Critical, Description: "Jackson enableDefaultTyping enables polymorphic deserialization (RCE)", CWEID: "CWE-502", OWASPCategory: "A08:2021-Software and Data Integrity Failures"},

		// ObjectInputStream.readUnshared (CWE-502)
		{ID: "java.objectinputstream.readunshared", Category: taint.SnkDeserialize, Language: rules.LangJava, Pattern: `ObjectInputStream.*\.readUnshared\s*\(`, ObjectType: "ObjectInputStream", MethodName: "readUnshared", DangerousArgs: []int{-1}, Severity: rules.Critical, Description: "Unsafe Java deserialization via readUnshared", CWEID: "CWE-502", OWASPCategory: "A08:2021-Software and Data Integrity Failures"},

		// XStream (CVE-2020-26217, CVE-2021-21344, CVE-2021-39149)
		{ID: "java.xstream.fromxml", Category: taint.SnkDeserialize, Language: rules.LangJava, Pattern: `(?:XStream|xstream)\.fromXML\s*\(`, ObjectType: "XStream", MethodName: "fromXML", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "XStream XML deserialization (RCE via gadget chains)", CWEID: "CWE-502", OWASPCategory: "A08:2021-Software and Data Integrity Failures"},
		{ID: "java.xstream.unmarshal", Category: taint.SnkDeserialize, Language: rules.LangJava, Pattern: `(?:XStream|xstream)\.unmarshal\s*\(`, ObjectType: "XStream", MethodName: "unmarshal", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "XStream unmarshal deserialization (RCE via gadget chains)", CWEID: "CWE-502", OWASPCategory: "A08:2021-Software and Data Integrity Failures"},

		// SnakeYAML (CVE-2022-1471)
		{ID: "java.snakeyaml.load", Category: taint.SnkDeserialize, Language: rules.LangJava, Pattern: `(?:Yaml|yaml)\.load\s*\(`, ObjectType: "Yaml", MethodName: "load", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "SnakeYAML unsafe load (arbitrary object instantiation)", CWEID: "CWE-502", OWASPCategory: "A08:2021-Software and Data Integrity Failures"},
		{ID: "java.snakeyaml.loadall", Category: taint.SnkDeserialize, Language: rules.LangJava, Pattern: `(?:Yaml|yaml)\.loadAll\s*\(`, ObjectType: "Yaml", MethodName: "loadAll", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "SnakeYAML unsafe loadAll (arbitrary object instantiation)", CWEID: "CWE-502", OWASPCategory: "A08:2021-Software and Data Integrity Failures"},

		// Kryo (used in Apache Spark, Storm)
		{ID: "java.kryo.readobject", Category: taint.SnkDeserialize, Language: rules.LangJava, Pattern: `(?:Kryo|kryo)\.readObject\s*\(`, ObjectType: "Kryo", MethodName: "readObject", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "Kryo deserialization without class registration enforcement", CWEID: "CWE-502", OWASPCategory: "A08:2021-Software and Data Integrity Failures"},
		{ID: "java.kryo.readclassandobject", Category: taint.SnkDeserialize, Language: rules.LangJava, Pattern: `(?:Kryo|kryo)\.readClassAndObject\s*\(`, ObjectType: "Kryo", MethodName: "readClassAndObject", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "Kryo readClassAndObject allows arbitrary class instantiation", CWEID: "CWE-502", OWASPCategory: "A08:2021-Software and Data Integrity Failures"},

		// Hessian (Dubbo RCE — CVE-2020-1948)
		{ID: "java.hessian.readobject", Category: taint.SnkDeserialize, Language: rules.LangJava, Pattern: `(?:HessianInput|Hessian2Input).*\.readObject\s*\(`, ObjectType: "HessianInput", MethodName: "readObject", DangerousArgs: []int{-1}, Severity: rules.Critical, Description: "Hessian deserialization (Dubbo RCE chain)", CWEID: "CWE-502", OWASPCategory: "A08:2021-Software and Data Integrity Failures"},

		// Fastjson (CVE-2017-18349, CVE-2022-25845)
		{ID: "java.fastjson.parseobject", Category: taint.SnkDeserialize, Language: rules.LangJava, Pattern: `JSON\.parseObject\s*\(`, ObjectType: "JSON", MethodName: "parseObject", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "Fastjson JSON.parseObject with autoType enables arbitrary class loading", CWEID: "CWE-502", OWASPCategory: "A08:2021-Software and Data Integrity Failures"},
		{ID: "java.fastjson.parse", Category: taint.SnkDeserialize, Language: rules.LangJava, Pattern: `JSON\.parse\s*\(`, ObjectType: "JSON", MethodName: "parse", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "Fastjson JSON.parse with autoType enables arbitrary class loading", CWEID: "CWE-502", OWASPCategory: "A08:2021-Software and Data Integrity Failures"},

		// Jackson activateDefaultTyping without safe validator
		{ID: "java.jackson.activatedefaulttyping", Category: taint.SnkDeserialize, Language: rules.LangJava, Pattern: `(?:ObjectMapper|objectMapper|mapper)\.activateDefaultTyping\s*\(`, ObjectType: "ObjectMapper", MethodName: "activateDefaultTyping", DangerousArgs: []int{-1}, Severity: rules.Critical, Description: "Jackson activateDefaultTyping enables polymorphic deserialization (RCE)", CWEID: "CWE-502", OWASPCategory: "A08:2021-Software and Data Integrity Failures"},

		// Apache Commons file operations with tainted paths
		{ID: "java.commons.fileutils.writestringtofile", Category: taint.SnkFileWrite, Language: rules.LangJava, Pattern: `FileUtils\.writeStringToFile\s*\(`, ObjectType: "FileUtils", MethodName: "writeStringToFile", DangerousArgs: []int{0}, Severity: rules.High, Description: "Apache Commons FileUtils.writeStringToFile with tainted path", CWEID: "CWE-22", OWASPCategory: "A01:2021-Broken Access Control"},
		{ID: "java.commons.fileutils.copyfile", Category: taint.SnkFileWrite, Language: rules.LangJava, Pattern: `FileUtils\.copyFile\s*\(`, ObjectType: "FileUtils", MethodName: "copyFile", DangerousArgs: []int{0, 1}, Severity: rules.High, Description: "Apache Commons FileUtils.copyFile with tainted path", CWEID: "CWE-22", OWASPCategory: "A01:2021-Broken Access Control"},

		// HTTP header injection
		{ID: "java.servlet.setheader", Category: taint.SnkHeader, Language: rules.LangJava, Pattern: `response\.setHeader\s*\(`, ObjectType: "HttpServletResponse", MethodName: "setHeader", DangerousArgs: []int{1}, Severity: rules.Medium, Description: "HTTP response header injection", CWEID: "CWE-113", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.servlet.addheader", Category: taint.SnkHeader, Language: rules.LangJava, Pattern: `response\.addHeader\s*\(`, ObjectType: "HttpServletResponse", MethodName: "addHeader", DangerousArgs: []int{1}, Severity: rules.Medium, Description: "HTTP response header injection via addHeader", CWEID: "CWE-113", OWASPCategory: "A03:2021-Injection"},

		// Redis command injection (Jedis/Lettuce)
		{ID: "java.jedis.eval", Category: taint.SnkEval, Language: rules.LangJava, Pattern: `(?:jedis|Jedis)\.eval\s*\(`, ObjectType: "Jedis", MethodName: "eval", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "Redis Lua script evaluation with tainted script via Jedis", CWEID: "CWE-94", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.lettuce.dispatch", Category: taint.SnkCommand, Language: rules.LangJava, Pattern: `\.dispatch\s*\(`, ObjectType: "RedisCommands", MethodName: "dispatch", DangerousArgs: []int{0}, Severity: rules.High, Description: "Redis command dispatch with tainted arguments via Lettuce", CWEID: "CWE-77", OWASPCategory: "A03:2021-Injection"},

		// DNS lookup with tainted hostname
		{ID: "java.inetaddress.getbyname", Category: taint.SnkURLFetch, Language: rules.LangJava, Pattern: `InetAddress\.getByName\s*\(|InetAddress\.getAllByName\s*\(`, ObjectType: "InetAddress", MethodName: "getByName", DangerousArgs: []int{0}, Severity: rules.High, Description: "DNS lookup with tainted hostname (SSRF/DNS rebinding)", CWEID: "CWE-918", OWASPCategory: "A10:2021-Server-Side Request Forgery"},

		// SMTP email header injection (JavaMail)
		{ID: "java.javamail.transport.send", Category: taint.SnkHeader, Language: rules.LangJava, Pattern: `Transport\.send\s*\(|\.setRecipients\s*\(`, ObjectType: "javax.mail.Transport", MethodName: "send", DangerousArgs: []int{0}, Severity: rules.High, Description: "JavaMail send with tainted headers/recipients (email injection)", CWEID: "CWE-93", OWASPCategory: "A03:2021-Injection"},

		// Docker exec (docker-java)
		{ID: "java.docker.execstart", Category: taint.SnkCommand, Language: rules.LangJava, Pattern: `\.execStartCmd\s*\(|\.execCreateCmd\s*\(`, ObjectType: "DockerClient", MethodName: "execCreateCmd", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "Docker container exec with tainted command via docker-java", CWEID: "CWE-78", OWASPCategory: "A03:2021-Injection"},

		// Kafka message construction
		{ID: "java.kafka.producer.send", Category: taint.SnkCommand, Language: rules.LangJava, Pattern: `producer\.send\s*\(|KafkaProducer.*\.send\s*\(`, ObjectType: "KafkaProducer", MethodName: "send", DangerousArgs: []int{0}, Severity: rules.Medium, Description: "Kafka message produced with tainted data", CWEID: "CWE-77", OWASPCategory: "A03:2021-Injection"},

		// XPath injection
		{ID: "java.xpath.evaluate", Category: taint.SnkXPath, Language: rules.LangJava, Pattern: `(?:XPath|xpath)\.evaluate\s*\(`, ObjectType: "XPath", MethodName: "evaluate", DangerousArgs: []int{0}, Severity: rules.High, Description: "XPath evaluation with tainted expression", CWEID: "CWE-643", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.xpathexpression.evaluate", Category: taint.SnkXPath, Language: rules.LangJava, Pattern: `(?:XPathExpression|xpathExpr)\.evaluate\s*\(`, ObjectType: "XPathExpression", MethodName: "evaluate", DangerousArgs: []int{0}, Severity: rules.High, Description: "Compiled XPath evaluation with tainted input", CWEID: "CWE-643", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.xpathfactory.compile", Category: taint.SnkXPath, Language: rules.LangJava, Pattern: `XPathFactory.*\.newXPath\s*\(\s*\)\.compile\s*\(`, ObjectType: "XPathFactory", MethodName: "compile", DangerousArgs: []int{0}, Severity: rules.High, Description: "XPath compile with tainted expression string", CWEID: "CWE-643", OWASPCategory: "A03:2021-Injection"},

		// Template injection
		{ID: "java.velocity.mergetemplate", Category: taint.SnkTemplate, Language: rules.LangJava, Pattern: `(?:VelocityEngine|velocity|ve)\.mergeTemplate\s*\(`, ObjectType: "VelocityEngine", MethodName: "mergeTemplate", DangerousArgs: []int{0}, Severity: rules.High, Description: "Apache Velocity template merge with tainted data", CWEID: "CWE-1336", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.velocity.template.merge", Category: taint.SnkTemplate, Language: rules.LangJava, Pattern: `(?:Template|template)\.merge\s*\(`, ObjectType: "Template", MethodName: "merge", DangerousArgs: []int{0}, Severity: rules.High, Description: "Apache Velocity Template.merge with tainted context data", CWEID: "CWE-1336", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.freemarker.process", Category: taint.SnkTemplate, Language: rules.LangJava, Pattern: `(?:Template|template)\.process\s*\(`, ObjectType: "Template", MethodName: "process", DangerousArgs: []int{0}, Severity: rules.High, Description: "FreeMarker template processing with tainted data", CWEID: "CWE-1336", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.pebble.evaluate", Category: taint.SnkTemplate, Language: rules.LangJava, Pattern: `(?:PebbleTemplate|template)\.evaluate\s*\(`, ObjectType: "PebbleTemplate", MethodName: "evaluate", DangerousArgs: []int{0}, Severity: rules.High, Description: "Pebble template evaluation with tainted data", CWEID: "CWE-1336", OWASPCategory: "A03:2021-Injection"},

		// LDAP injection (deeper coverage)
		{ID: "java.spring.ldaptemplate.search", Category: taint.SnkLDAP, Language: rules.LangJava, Pattern: `(?:LdapTemplate|ldapTemplate)\.search\s*\(`, ObjectType: "LdapTemplate", MethodName: "search", DangerousArgs: []int{0}, Severity: rules.High, Description: "Spring LDAP template search with tainted filter", CWEID: "CWE-90", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.jndi.initialdircontext.search", Category: taint.SnkLDAP, Language: rules.LangJava, Pattern: `(?:InitialDirContext|dirContext|ctx)\.search\s*\(`, ObjectType: "InitialDirContext", MethodName: "search", DangerousArgs: []int{1}, Severity: rules.High, Description: "JNDI LDAP search with tainted filter", CWEID: "CWE-90", OWASPCategory: "A03:2021-Injection"},

		// Expression Language injection
		{ID: "java.el.createvalueexpression", Category: taint.SnkEval, Language: rules.LangJava, Pattern: `(?:ExpressionFactory|elFactory)\.createValueExpression\s*\(`, ObjectType: "ExpressionFactory", MethodName: "createValueExpression", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "EL expression evaluation with tainted input", CWEID: "CWE-917", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.spring.spel.parseexpression", Category: taint.SnkEval, Language: rules.LangJava, Pattern: `(?:SpelExpressionParser|expressionParser)\.parseExpression\s*\(`, ObjectType: "SpelExpressionParser", MethodName: "parseExpression", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "Spring Expression Language with tainted input", CWEID: "CWE-917", OWASPCategory: "A03:2021-Injection"},

		// HTTP Content-Type injection
		{ID: "java.servlet.setcontenttype", Category: taint.SnkHeader, Language: rules.LangJava, Pattern: `response\.setContentType\s*\(`, ObjectType: "HttpServletResponse", MethodName: "setContentType", DangerousArgs: []int{0}, Severity: rules.Medium, Description: "HTTP Content-Type header with tainted value", CWEID: "CWE-113", OWASPCategory: "A03:2021-Injection"},

		// --- NIO File Operations (CWE-22) ---
		{ID: "java.nio.files.write", Category: taint.SnkFileWrite, Language: rules.LangJava, Pattern: `Files\.write\s*\(`, ObjectType: "Files", MethodName: "write", DangerousArgs: []int{0}, Severity: rules.High, Description: "NIO Files.write with potentially tainted path", CWEID: "CWE-22", OWASPCategory: "A01:2021-Broken Access Control"},
		{ID: "java.nio.files.copy", Category: taint.SnkFileWrite, Language: rules.LangJava, Pattern: `Files\.copy\s*\(`, ObjectType: "Files", MethodName: "copy", DangerousArgs: []int{0, 1}, Severity: rules.High, Description: "NIO Files.copy with potentially tainted path", CWEID: "CWE-22", OWASPCategory: "A01:2021-Broken Access Control"},
		{ID: "java.nio.files.move", Category: taint.SnkFileWrite, Language: rules.LangJava, Pattern: `Files\.move\s*\(`, ObjectType: "Files", MethodName: "move", DangerousArgs: []int{0, 1}, Severity: rules.High, Description: "NIO Files.move with potentially tainted path", CWEID: "CWE-22", OWASPCategory: "A01:2021-Broken Access Control"},
		{ID: "java.nio.files.createsymboliclink", Category: taint.SnkFileWrite, Language: rules.LangJava, Pattern: `Files\.createSymbolicLink\s*\(`, ObjectType: "Files", MethodName: "createSymbolicLink", DangerousArgs: []int{0, 1}, Severity: rules.High, Description: "NIO symlink creation with potentially tainted paths (symlink attack)", CWEID: "CWE-59", OWASPCategory: "A01:2021-Broken Access Control"},
		{ID: "java.nio.files.createdirectories", Category: taint.SnkFileWrite, Language: rules.LangJava, Pattern: `Files\.createDirectories\s*\(|Files\.createDirectory\s*\(`, ObjectType: "Files", MethodName: "createDirectories", DangerousArgs: []int{0}, Severity: rules.High, Description: "NIO directory creation with potentially tainted path", CWEID: "CWE-22", OWASPCategory: "A01:2021-Broken Access Control"},
		{ID: "java.nio.paths.get", Category: taint.SnkFileWrite, Language: rules.LangJava, Pattern: `Paths\.get\s*\(`, ObjectType: "Paths", MethodName: "get", DangerousArgs: []int{0}, Severity: rules.Medium, Description: "Path construction with potentially tainted components", CWEID: "CWE-22", OWASPCategory: "A01:2021-Broken Access Control"},

		// --- SSRF via newer HTTP clients (CWE-918) ---
		{ID: "java.httpclient.send", Category: taint.SnkURLFetch, Language: rules.LangJava, Pattern: `HttpClient.*\.send\s*\(|httpClient\.send\s*\(`, ObjectType: "HttpClient", MethodName: "send", DangerousArgs: []int{0}, Severity: rules.High, Description: "Java 11+ HttpClient.send with potentially tainted request (SSRF)", CWEID: "CWE-918", OWASPCategory: "A10:2021-Server-Side Request Forgery"},
		{ID: "java.spring.webclient", Category: taint.SnkURLFetch, Language: rules.LangJava, Pattern: `WebClient.*\.uri\s*\(|webClient\.get\s*\(\s*\)\s*\.uri\s*\(`, ObjectType: "WebClient", MethodName: "uri", DangerousArgs: []int{0}, Severity: rules.High, Description: "Spring WebClient with potentially tainted URI (SSRF)", CWEID: "CWE-918", OWASPCategory: "A10:2021-Server-Side Request Forgery"},
		{ID: "java.uri.create", Category: taint.SnkURLFetch, Language: rules.LangJava, Pattern: `URI\.create\s*\(`, ObjectType: "URI", MethodName: "create", DangerousArgs: []int{0}, Severity: rules.High, Description: "URI creation with potentially tainted string (SSRF)", CWEID: "CWE-918", OWASPCategory: "A10:2021-Server-Side Request Forgery"},

		// --- Apache HttpClient SSRF (CWE-918) ---
		{ID: "java.apache.httpclient.httpget", Category: taint.SnkURLFetch, Language: rules.LangJava, Pattern: `new\s+HttpGet\s*\(`, ObjectType: "HttpGet", MethodName: "HttpGet", DangerousArgs: []int{0}, Severity: rules.High, Description: "Apache HttpClient HttpGet with tainted URL (SSRF)", CWEID: "CWE-918", OWASPCategory: "A10:2021-Server-Side Request Forgery"},
		{ID: "java.apache.httpclient.httppost", Category: taint.SnkURLFetch, Language: rules.LangJava, Pattern: `new\s+HttpPost\s*\(`, ObjectType: "HttpPost", MethodName: "HttpPost", DangerousArgs: []int{0}, Severity: rules.High, Description: "Apache HttpClient HttpPost with tainted URL (SSRF)", CWEID: "CWE-918", OWASPCategory: "A10:2021-Server-Side Request Forgery"},
		{ID: "java.apache.httpclient.httpput", Category: taint.SnkURLFetch, Language: rules.LangJava, Pattern: `new\s+HttpPut\s*\(`, ObjectType: "HttpPut", MethodName: "HttpPut", DangerousArgs: []int{0}, Severity: rules.High, Description: "Apache HttpClient HttpPut with tainted URL (SSRF)", CWEID: "CWE-918", OWASPCategory: "A10:2021-Server-Side Request Forgery"},
		{ID: "java.apache.httpclient.httpdelete", Category: taint.SnkURLFetch, Language: rules.LangJava, Pattern: `new\s+HttpDelete\s*\(`, ObjectType: "HttpDelete", MethodName: "HttpDelete", DangerousArgs: []int{0}, Severity: rules.High, Description: "Apache HttpClient HttpDelete with tainted URL (SSRF)", CWEID: "CWE-918", OWASPCategory: "A10:2021-Server-Side Request Forgery"},
		{ID: "java.apache.httpclient.httppatch", Category: taint.SnkURLFetch, Language: rules.LangJava, Pattern: `new\s+HttpPatch\s*\(`, ObjectType: "HttpPatch", MethodName: "HttpPatch", DangerousArgs: []int{0}, Severity: rules.High, Description: "Apache HttpClient HttpPatch with tainted URL (SSRF)", CWEID: "CWE-918", OWASPCategory: "A10:2021-Server-Side Request Forgery"},
		{ID: "java.apache.httpclient.seturi", Category: taint.SnkURLFetch, Language: rules.LangJava, Pattern: `\.setURI\s*\(`, ObjectType: "HttpRequestBase", MethodName: "setURI", DangerousArgs: []int{0}, Severity: rules.High, Description: "Apache HttpClient setURI with tainted URI (SSRF)", CWEID: "CWE-918", OWASPCategory: "A10:2021-Server-Side Request Forgery"},
		{ID: "java.apache.httpclient.uribuilder", Category: taint.SnkURLFetch, Language: rules.LangJava, Pattern: `new\s+URIBuilder\s*\(`, ObjectType: "URIBuilder", MethodName: "URIBuilder", DangerousArgs: []int{0}, Severity: rules.High, Description: "Apache URIBuilder with tainted base URL (SSRF)", CWEID: "CWE-918", OWASPCategory: "A10:2021-Server-Side Request Forgery"},

		// --- OkHttp SSRF (CWE-918) ---
		{ID: "java.okhttp3.request.url", Category: taint.SnkURLFetch, Language: rules.LangJava, Pattern: `new\s+Request\.Builder\s*\(\s*\)\.url\s*\(`, ObjectType: "Request.Builder", MethodName: "url", DangerousArgs: []int{0}, Severity: rules.High, Description: "OkHttp Request.Builder.url with tainted URL (SSRF)", CWEID: "CWE-918", OWASPCategory: "A10:2021-Server-Side Request Forgery"},
		{ID: "java.okhttp3.newcall", Category: taint.SnkURLFetch, Language: rules.LangJava, Pattern: `\.newCall\s*\(`, ObjectType: "", MethodName: "newCall", DangerousArgs: []int{0}, Severity: rules.High, Description: "OkHttp newCall execution with tainted request (SSRF)", CWEID: "CWE-918", OWASPCategory: "A10:2021-Server-Side Request Forgery"},

		// --- Reactor Netty HttpClient SSRF (CWE-918) ---
		{ID: "java.reactor.netty.baseurl", Category: taint.SnkURLFetch, Language: rules.LangJava, Pattern: `HttpClient\.create\s*\(\s*\)[\s\S]{0,100}\.baseUrl\s*\(`, ObjectType: "HttpClient", MethodName: "baseUrl", DangerousArgs: []int{0}, Severity: rules.High, Description: "Reactor Netty HttpClient.baseUrl with tainted URL (SSRF)", CWEID: "CWE-918", OWASPCategory: "A10:2021-Server-Side Request Forgery"},

		// --- Google HTTP Client SSRF (CWE-918) ---
		{ID: "java.google.httpclient.genericurl", Category: taint.SnkURLFetch, Language: rules.LangJava, Pattern: `new\s+GenericUrl\s*\(`, ObjectType: "GenericUrl", MethodName: "GenericUrl", DangerousArgs: []int{0}, Severity: rules.High, Description: "Google HTTP Client GenericUrl with tainted URL (SSRF)", CWEID: "CWE-918", OWASPCategory: "A10:2021-Server-Side Request Forgery"},

		// --- String.format injection (CWE-134) ---
		{ID: "java.string.format", Category: taint.SnkLog, Language: rules.LangJava, Pattern: `String\.format\s*\(`, ObjectType: "String", MethodName: "format", DangerousArgs: []int{0}, Severity: rules.Medium, Description: "String.format with potentially tainted format string", CWEID: "CWE-134", OWASPCategory: "A03:2021-Injection"},

		// --- OGNL injection (CWE-917) ---
		{ID: "java.ognl.getvalue", Category: taint.SnkEval, Language: rules.LangJava, Pattern: `Ognl\.getValue\s*\(|OgnlUtil.*\.getValue\s*\(`, ObjectType: "Ognl", MethodName: "getValue", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "OGNL expression evaluation with tainted input (RCE)", CWEID: "CWE-917", OWASPCategory: "A03:2021-Injection"},

		// --- Cookie injection (CWE-113) ---
		{ID: "java.servlet.addcookie", Category: taint.SnkHeader, Language: rules.LangJava, Pattern: `response\.addCookie\s*\(`, ObjectType: "HttpServletResponse", MethodName: "addCookie", DangerousArgs: []int{0}, Severity: rules.Medium, Description: "HTTP cookie set with potentially tainted value", CWEID: "CWE-113", OWASPCategory: "A03:2021-Injection"},

		// --- PreparedStatement (CWE-89) — SQL is concatenated before prepare ---
		{ID: "java.sql.connection.preparestatement", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `(?:connection|conn|con|c)\.prepareStatement\s*\(`, ObjectType: "Connection", MethodName: "prepareStatement", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "PreparedStatement with concatenated SQL (injection)", CWEID: "CWE-89", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.sql.connection.preparecall", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `(?:connection|conn|con|c)\.prepareCall\s*\(`, ObjectType: "Connection", MethodName: "prepareCall", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "CallableStatement with concatenated SQL (injection)", CWEID: "CWE-89", OWASPCategory: "A03:2021-Injection"},

		// --- XSS via PrintWriter.format/printf (CWE-79) ---
		{ID: "java.servlet.writer.format", Category: taint.SnkHTMLOutput, Language: rules.LangJava, Pattern: `(?:response\.getWriter\s*\(\s*\)\s*\.|writer\.)format\s*\(`, ObjectType: "PrintWriter", MethodName: "format", DangerousArgs: []int{-1}, Severity: rules.High, Description: "HTTP response format (XSS)", CWEID: "CWE-79", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.servlet.writer.printf", Category: taint.SnkHTMLOutput, Language: rules.LangJava, Pattern: `(?:response\.getWriter\s*\(\s*\)\s*\.|writer\.)printf\s*\(`, ObjectType: "PrintWriter", MethodName: "printf", DangerousArgs: []int{-1}, Severity: rules.High, Description: "HTTP response printf (XSS)", CWEID: "CWE-79", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.servlet.writer.print", Category: taint.SnkHTMLOutput, Language: rules.LangJava, Pattern: `response\.getWriter\s*\(\s*\)\s*\.print\s*\(`, ObjectType: "PrintWriter", MethodName: "print", DangerousArgs: []int{0}, Severity: rules.High, Description: "HTTP response print (XSS)", CWEID: "CWE-79", OWASPCategory: "A03:2021-Injection"},

		// --- Spring JdbcTemplate.queryForRowSet (CWE-89) ---
		{ID: "java.spring.jdbctemplate.queryforrowset", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `(?:JDBCtemplate|jdbcTemplate)\.queryForRowSet\s*\(`, ObjectType: "JdbcTemplate", MethodName: "queryForRowSet", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "Spring JdbcTemplate.queryForRowSet with potential SQL injection", CWEID: "CWE-89", OWASPCategory: "A03:2021-Injection"},

		// --- Weak hash with variable algorithm (CWE-328) ---
		{ID: "java.crypto.messagedigest.getinstance.var", Category: taint.SnkCrypto, Language: rules.LangJava, Pattern: `MessageDigest\.getInstance\s*\(\s*[a-zA-Z]`, ObjectType: "MessageDigest", MethodName: "getInstance", DangerousArgs: []int{0}, Severity: rules.Medium, Description: "MessageDigest.getInstance with variable algorithm (may use weak hash)", CWEID: "CWE-328", OWASPCategory: "A02:2021-Cryptographic Failures"},

		// --- Trust boundary violation (CWE-501) ---
		{ID: "java.session.setattribute", Category: taint.SnkTrustBoundary, Language: rules.LangJava, Pattern: `(?:session|getSession\s*\(\s*\))\.setAttribute\s*\(`, ObjectType: "HttpSession", MethodName: "setAttribute", DangerousArgs: []int{-1}, Severity: rules.High, Description: "Trust boundary violation: tainted data stored in session", CWEID: "CWE-501", OWASPCategory: "A04:2021-Insecure Design"},
		{ID: "java.session.putvalue", Category: taint.SnkTrustBoundary, Language: rules.LangJava, Pattern: `(?:session|getSession\s*\(\s*\))\.putValue\s*\(`, ObjectType: "HttpSession", MethodName: "putValue", DangerousArgs: []int{-1}, Severity: rules.High, Description: "Trust boundary violation: tainted data stored in session via putValue", CWEID: "CWE-501", OWASPCategory: "A04:2021-Insecure Design"},

		// --- Spring JDBCTemplate SQL injection (CWE-89) ---
		{ID: "java.spring.jdbctemplate.queryformap", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `JDBCtemplate\.queryForMap\s*\(|jdbcTemplate\.queryForMap\s*\(`, ObjectType: "JdbcTemplate", MethodName: "queryForMap", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "Spring JdbcTemplate.queryForMap with potential SQL injection", CWEID: "CWE-89", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.spring.jdbctemplate.queryforobject", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `(?:JDBCtemplate|jdbcTemplate)\.queryForObject\s*\(`, ObjectType: "JdbcTemplate", MethodName: "queryForObject", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "Spring JdbcTemplate.queryForObject with potential SQL injection", CWEID: "CWE-89", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.spring.jdbctemplate.queryforlist", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `(?:JDBCtemplate|jdbcTemplate)\.queryForList\s*\(`, ObjectType: "JdbcTemplate", MethodName: "queryForList", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "Spring JdbcTemplate.queryForList with potential SQL injection", CWEID: "CWE-89", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.spring.jdbctemplate.query", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `(?:JDBCtemplate|jdbcTemplate)\.query\s*\(`, ObjectType: "JdbcTemplate", MethodName: "query", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "Spring JdbcTemplate.query with potential SQL injection", CWEID: "CWE-89", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.spring.jdbctemplate.update", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `(?:JDBCtemplate|jdbcTemplate)\.update\s*\(`, ObjectType: "JdbcTemplate", MethodName: "update", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "Spring JdbcTemplate.update with potential SQL injection", CWEID: "CWE-89", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.spring.jdbctemplate.execute", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `(?:JDBCtemplate|jdbcTemplate)\.execute\s*\(`, ObjectType: "JdbcTemplate", MethodName: "execute", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "Spring JdbcTemplate.execute with potential SQL injection", CWEID: "CWE-89", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.spring.jdbctemplate.batchupdate", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `(?:JDBCtemplate|jdbcTemplate)\.batchUpdate\s*\(`, ObjectType: "JdbcTemplate", MethodName: "batchUpdate", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "Spring JdbcTemplate.batchUpdate with potential SQL injection", CWEID: "CWE-89", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.spring.jdbctemplate.queryforlong", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `(?:JDBCtemplate|jdbcTemplate)\.queryForLong\s*\(`, ObjectType: "JdbcTemplate", MethodName: "queryForLong", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "Spring JdbcTemplate.queryForLong with potential SQL injection", CWEID: "CWE-89", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.spring.jdbctemplate.queryforint", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `(?:JDBCtemplate|jdbcTemplate)\.queryForInt\s*\(`, ObjectType: "JdbcTemplate", MethodName: "queryForInt", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "Spring JdbcTemplate.queryForInt with potential SQL injection", CWEID: "CWE-89", OWASPCategory: "A03:2021-Injection"},

		// --- java.net.URI path traversal (CWE-22) ---
		{ID: "java.net.uri.new", Category: taint.SnkFileWrite, Language: rules.LangJava, Pattern: `new\s+(?:java\.net\.)?URI\s*\(`, ObjectType: "URI", MethodName: "URI", DangerousArgs: []int{0, 2, 4}, Severity: rules.High, Description: "URI construction with potentially tainted path component", CWEID: "CWE-22", OWASPCategory: "A01:2021-Broken Access Control"},
		{ID: "java.io.fileinputstream", Category: taint.SnkFileWrite, Language: rules.LangJava, Pattern: `new\s+FileInputStream\s*\(`, ObjectType: "FileInputStream", MethodName: "FileInputStream", DangerousArgs: []int{0}, Severity: rules.High, Description: "FileInputStream with potential path traversal", CWEID: "CWE-22", OWASPCategory: "A01:2021-Broken Access Control"},

		// --- LDAP injection additional patterns (CWE-90) ---
		{ID: "java.naming.ldap.search", Category: taint.SnkLDAP, Language: rules.LangJava, Pattern: `(?:LdapContext|ldapContext|NamingEnumeration).*\.search\s*\(`, ObjectType: "LdapContext", MethodName: "search", DangerousArgs: []int{1}, Severity: rules.High, Description: "LDAP search with tainted filter", CWEID: "CWE-90", OWASPCategory: "A03:2021-Injection"},

		// --- XPath injection additional (CWE-643) ---
		{ID: "java.xpath.compile", Category: taint.SnkXPath, Language: rules.LangJava, Pattern: `(?:XPath|xpath)\.compile\s*\(`, ObjectType: "XPath", MethodName: "compile", DangerousArgs: []int{0}, Severity: rules.High, Description: "XPath compilation with tainted expression", CWEID: "CWE-643", OWASPCategory: "A03:2021-Injection"},

		// --- JOOQ SQL injection (CWE-89) ---
		{ID: "java.jooq.plainSQL", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `DSL\.(query|resultQuery|field)\(`, ObjectType: "DSL", MethodName: "query/resultQuery/field", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "JOOQ plain SQL via DSL.query()/resultQuery()/field() with potentially tainted input", CWEID: "CWE-89", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.jooq.sql", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `DSL\.sql\(`, ObjectType: "DSL", MethodName: "sql", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "JOOQ raw SQL fragment via DSL.sql() with potentially tainted input", CWEID: "CWE-89", OWASPCategory: "A03:2021-Injection"},

		// --- File read path traversal (CWE-22) ---
		{ID: "java.nio.files.readallbytes", Category: taint.SnkFileRead, Language: rules.LangJava, Pattern: `Files\.readAllBytes\s*\(`, ObjectType: "Files", MethodName: "readAllBytes", DangerousArgs: []int{0}, Severity: rules.High, Description: "NIO Files.readAllBytes with potential path traversal", CWEID: "CWE-22", OWASPCategory: "A01:2021-Broken Access Control"},
		{ID: "java.nio.files.readstring", Category: taint.SnkFileRead, Language: rules.LangJava, Pattern: `Files\.readString\s*\(`, ObjectType: "Files", MethodName: "readString", DangerousArgs: []int{0}, Severity: rules.High, Description: "NIO Files.readString with potential path traversal", CWEID: "CWE-22", OWASPCategory: "A01:2021-Broken Access Control"},
		{ID: "java.nio.files.readalllines", Category: taint.SnkFileRead, Language: rules.LangJava, Pattern: `Files\.readAllLines\s*\(`, ObjectType: "Files", MethodName: "readAllLines", DangerousArgs: []int{0}, Severity: rules.High, Description: "NIO Files.readAllLines with potential path traversal", CWEID: "CWE-22", OWASPCategory: "A01:2021-Broken Access Control"},
		{ID: "java.nio.files.lines", Category: taint.SnkFileRead, Language: rules.LangJava, Pattern: `Files\.lines\s*\(`, ObjectType: "Files", MethodName: "lines", DangerousArgs: []int{0}, Severity: rules.High, Description: "NIO Files.lines with potential path traversal", CWEID: "CWE-22", OWASPCategory: "A01:2021-Broken Access Control"},
		{ID: "java.nio.files.newinputstream", Category: taint.SnkFileRead, Language: rules.LangJava, Pattern: `Files\.newInputStream\s*\(`, ObjectType: "Files", MethodName: "newInputStream", DangerousArgs: []int{0}, Severity: rules.High, Description: "NIO Files.newInputStream with potential path traversal", CWEID: "CWE-22", OWASPCategory: "A01:2021-Broken Access Control"},
		{ID: "java.nio.files.newbufferedreader", Category: taint.SnkFileRead, Language: rules.LangJava, Pattern: `Files\.newBufferedReader\s*\(`, ObjectType: "Files", MethodName: "newBufferedReader", DangerousArgs: []int{0}, Severity: rules.High, Description: "NIO Files.newBufferedReader with potential path traversal", CWEID: "CWE-22", OWASPCategory: "A01:2021-Broken Access Control"},
		{ID: "java.io.randomaccessfile", Category: taint.SnkFileRead, Language: rules.LangJava, Pattern: `new\s+RandomAccessFile\s*\(`, ObjectType: "RandomAccessFile", MethodName: "RandomAccessFile", DangerousArgs: []int{0}, Severity: rules.High, Description: "RandomAccessFile with potential path traversal", CWEID: "CWE-22", OWASPCategory: "A01:2021-Broken Access Control"},
		{ID: "java.commons.fileutils.readfiletostring", Category: taint.SnkFileRead, Language: rules.LangJava, Pattern: `FileUtils\.readFileToString\s*\(`, ObjectType: "FileUtils", MethodName: "readFileToString", DangerousArgs: []int{0}, Severity: rules.High, Description: "Apache Commons FileUtils.readFileToString with potential path traversal", CWEID: "CWE-22", OWASPCategory: "A01:2021-Broken Access Control"},
		{ID: "java.commons.fileutils.readlines", Category: taint.SnkFileRead, Language: rules.LangJava, Pattern: `FileUtils\.readLines\s*\(`, ObjectType: "FileUtils", MethodName: "readLines", DangerousArgs: []int{0}, Severity: rules.High, Description: "Apache Commons FileUtils.readLines with potential path traversal", CWEID: "CWE-22", OWASPCategory: "A01:2021-Broken Access Control"},

		// --- MongoDB NoSQL Injection (CWE-943) ---
		// MongoDB Java Driver — MongoCollection methods with tainted filter/query documents.
		// ObjectType left empty to match any receiver (same pattern as JS Mongoose sinks),
		// since variable names for MongoCollection vary widely (collection, col, users, etc.).
		// Taint gating prevents false positives on non-MongoDB .find() calls.
		{ID: "java.mongodb.collection.find", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `\.find\s*\(`, ObjectType: "", MethodName: "find", DangerousArgs: []int{0}, Severity: rules.High, Description: "MongoDB find() with tainted filter document (NoSQL injection)", CWEID: "CWE-943", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.mongodb.collection.aggregate", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `\.aggregate\s*\(`, ObjectType: "", MethodName: "aggregate", DangerousArgs: []int{0}, Severity: rules.High, Description: "MongoDB aggregate() with tainted pipeline (NoSQL injection)", CWEID: "CWE-943", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.mongodb.collection.updateone", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `\.updateOne\s*\(`, ObjectType: "", MethodName: "updateOne", DangerousArgs: []int{0}, Severity: rules.High, Description: "MongoDB updateOne() with tainted filter/update (NoSQL injection)", CWEID: "CWE-943", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.mongodb.collection.updatemany", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `\.updateMany\s*\(`, ObjectType: "", MethodName: "updateMany", DangerousArgs: []int{0}, Severity: rules.High, Description: "MongoDB updateMany() with tainted filter/update (NoSQL injection)", CWEID: "CWE-943", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.mongodb.collection.deleteone", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `\.deleteOne\s*\(`, ObjectType: "", MethodName: "deleteOne", DangerousArgs: []int{0}, Severity: rules.High, Description: "MongoDB deleteOne() with tainted filter (NoSQL injection)", CWEID: "CWE-943", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.mongodb.collection.deletemany", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `\.deleteMany\s*\(`, ObjectType: "", MethodName: "deleteMany", DangerousArgs: []int{0}, Severity: rules.High, Description: "MongoDB deleteMany() with tainted filter (NoSQL injection)", CWEID: "CWE-943", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.mongodb.collection.findoneandupdate", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `\.findOneAndUpdate\s*\(`, ObjectType: "", MethodName: "findOneAndUpdate", DangerousArgs: []int{0}, Severity: rules.High, Description: "MongoDB findOneAndUpdate() with tainted filter (NoSQL injection)", CWEID: "CWE-943", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.mongodb.collection.findoneanddelete", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `\.findOneAndDelete\s*\(`, ObjectType: "", MethodName: "findOneAndDelete", DangerousArgs: []int{0}, Severity: rules.High, Description: "MongoDB findOneAndDelete() with tainted filter (NoSQL injection)", CWEID: "CWE-943", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.mongodb.collection.countdocuments", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `\.countDocuments\s*\(`, ObjectType: "", MethodName: "countDocuments", DangerousArgs: []int{0}, Severity: rules.High, Description: "MongoDB countDocuments() with tainted filter (NoSQL injection)", CWEID: "CWE-943", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.mongodb.collection.distinct", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `\.distinct\s*\(`, ObjectType: "", MethodName: "distinct", DangerousArgs: []int{0}, Severity: rules.High, Description: "MongoDB distinct() with tainted filter (NoSQL injection)", CWEID: "CWE-943", OWASPCategory: "A03:2021-Injection"},
		// BasicDBObject.parse — raw JSON query construction
		{ID: "java.mongodb.basicdbobject.parse", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `BasicDBObject\.parse\s*\(`, ObjectType: "BasicDBObject", MethodName: "parse", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "MongoDB BasicDBObject.parse() with tainted JSON string (NoSQL injection)", CWEID: "CWE-943", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.mongodb.document.parse", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `Document\.parse\s*\(`, ObjectType: "Document", MethodName: "parse", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "MongoDB Document.parse() with tainted JSON string (NoSQL injection)", CWEID: "CWE-943", OWASPCategory: "A03:2021-Injection"},

		// Spring Data MongoDB — MongoTemplate methods
		{ID: "java.spring.mongotemplate.find", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `mongoTemplate\.find\s*\(`, ObjectType: "MongoTemplate", MethodName: "find", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "Spring MongoTemplate.find() with tainted query (NoSQL injection)", CWEID: "CWE-943", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.spring.mongotemplate.findone", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `mongoTemplate\.findOne\s*\(`, ObjectType: "MongoTemplate", MethodName: "findOne", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "Spring MongoTemplate.findOne() with tainted query (NoSQL injection)", CWEID: "CWE-943", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.spring.mongotemplate.findandmodify", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `mongoTemplate\.findAndModify\s*\(`, ObjectType: "MongoTemplate", MethodName: "findAndModify", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "Spring MongoTemplate.findAndModify() with tainted query (NoSQL injection)", CWEID: "CWE-943", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.spring.mongotemplate.findandremove", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `mongoTemplate\.findAndRemove\s*\(`, ObjectType: "MongoTemplate", MethodName: "findAndRemove", DangerousArgs: []int{0}, Severity: rules.Critical, Description: "Spring MongoTemplate.findAndRemove() with tainted query (NoSQL injection)", CWEID: "CWE-943", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.spring.mongotemplate.remove", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `mongoTemplate\.remove\s*\(`, ObjectType: "MongoTemplate", MethodName: "remove", DangerousArgs: []int{0}, Severity: rules.High, Description: "Spring MongoTemplate.remove() with tainted query (NoSQL injection)", CWEID: "CWE-943", OWASPCategory: "A03:2021-Injection"},
		{ID: "java.spring.mongotemplate.count", Category: taint.SnkSQLQuery, Language: rules.LangJava, Pattern: `mongoTemplate\.count\s*\(`, ObjectType: "MongoTemplate", MethodName: "count", DangerousArgs: []int{0}, Severity: rules.High, Description: "Spring MongoTemplate.count() with tainted query (NoSQL injection)", CWEID: "CWE-943", OWASPCategory: "A03:2021-Injection"},
	}
}
