// Package fpfilter provides false-positive filtering helpers used across
// the scanner and individual rule packages.  All functions are pure
// (no side effects) and safe for concurrent use.
package fpfilter

import (
	"path/filepath"
	"strings"
)

// ---------------------------------------------------------------------------
// Generated code detection
// ---------------------------------------------------------------------------

// generatedMarkers are strings that, when found in the first few lines of a
// file, indicate the file was auto-generated and should be skipped.
var generatedMarkers = []string{
	"// Code generated",
	"// DO NOT EDIT",
	"/* Code generated",
	"/* DO NOT EDIT",
	"# Code generated",
	"# DO NOT EDIT",
	"@generated",
	"auto-generated",
	"AUTO-GENERATED",
	"autogenerated",
	"AUTOGENERATED",
	"This file is generated",
	"This file was generated",
	"Generated by",
	"generated by",
}

// generatedPathPatterns are path substrings/suffixes that indicate generated
// files or vendored dependencies.
var generatedPathPatterns = []string{
	".pb.go",
	".pb.cc",
	".pb.h",
	"_generated.go",
	"_gen.go",
	".gen.go",
	".gen.ts",
	".generated.cs",
	"_generated.rs",
	"/node_modules/",
	"/vendor/",
	"/dist/",
	"/build/",
	"/__generated__/",
	"/generated/",
	".min.js",
	".min.css",
	".bundle.js",
}

// IsGeneratedFile returns true if the file at filePath with the given content
// looks like it was auto-generated or is vendored/third-party code.
// content may be empty; in that case only the path is checked.
func IsGeneratedFile(filePath string, content string) bool {
	// Normalise path separators for cross-platform matching.
	// Prepend "/" so patterns like "/vendor/" also match relative paths
	// that start with "vendor/".
	norm := "/" + filepath.ToSlash(filePath)

	for _, pat := range generatedPathPatterns {
		if strings.Contains(norm, pat) {
			return true
		}
	}

	// Check the first 2 KB (or first ~40 lines) for marker strings.
	header := content
	if len(header) > 2048 {
		header = header[:2048]
	}
	lower := strings.ToLower(header)
	for _, marker := range generatedMarkers {
		if strings.Contains(lower, strings.ToLower(marker)) {
			return true
		}
	}

	return false
}

// ---------------------------------------------------------------------------
// Comment detection
// ---------------------------------------------------------------------------

// IsCommentLine returns true if the trimmed line starts with a single-line or
// block-comment introducer in any of the supported languages.
func IsCommentLine(line string) bool {
	trimmed := strings.TrimSpace(line)
	if trimmed == "" {
		return false
	}
	return strings.HasPrefix(trimmed, "//") ||
		strings.HasPrefix(trimmed, "#") ||
		strings.HasPrefix(trimmed, "--") ||
		strings.HasPrefix(trimmed, ";") ||
		strings.HasPrefix(trimmed, "%") ||
		strings.HasPrefix(trimmed, "/*") ||
		strings.HasPrefix(trimmed, "* ") ||
		strings.HasPrefix(trimmed, "*\t") ||
		trimmed == "*" ||
		strings.HasPrefix(trimmed, "*/") ||
		strings.HasPrefix(trimmed, "<!--") ||
		strings.HasPrefix(trimmed, "REM ") ||
		strings.HasPrefix(trimmed, "rem ")
}

// InBlockComment tracks whether a given line index falls inside a multi-line
// block comment. It does a single pass over all lines, tracking nesting for
// /* ... */ and <!-- ... --> style comments.
//
// The returned slice has the same length as lines; result[i] is true when
// line i is entirely inside a block comment.
func InBlockComment(lines []string) []bool {
	n := len(lines)
	result := make([]bool, n)
	inBlock := false

	for i, line := range lines {
		trimmed := strings.TrimSpace(line)

		if inBlock {
			result[i] = true
			// Check if block comment ends on this line.
			if strings.Contains(trimmed, "*/") || strings.Contains(trimmed, "-->") {
				inBlock = false
			}
			continue
		}

		// Not currently in a block comment.
		// Check if a block comment opens on this line.
		if openIdx := blockCommentOpen(trimmed); openIdx >= 0 {
			// If the line also closes on the same line, it is a single-line block comment
			// (e.g.  /* foo */ ).  Mark it as a comment line only if nothing
			// meaningful precedes the opening marker.
			closeIdx := blockCommentClose(trimmed[openIdx:])
			if closeIdx >= 0 {
				// Single-line block comment; only mark as comment if the
				// opener is at the start (after whitespace).
				if openIdx == 0 {
					result[i] = true
				}
			} else {
				// Block comment continues to subsequent lines.
				if openIdx == 0 {
					result[i] = true
				}
				inBlock = true
			}
		}
	}

	return result
}

// blockCommentOpen returns the index of the first block-comment opener in
// the trimmed line, or -1 if none found.
func blockCommentOpen(trimmed string) int {
	idx := -1
	for _, opener := range []string{"/*", "<!--", `"""`} {
		if i := strings.Index(trimmed, opener); i >= 0 {
			if idx < 0 || i < idx {
				idx = i
			}
		}
	}
	return idx
}

// blockCommentClose returns the index of the first block-comment closer
// after the opener, or -1 if none.
func blockCommentClose(s string) int {
	// Skip past the opener itself.
	for _, pair := range []struct{ open, close string }{
		{"/*", "*/"},
		{"<!--", "-->"},
		{`"""`, `"""`},
	} {
		if strings.HasPrefix(s, pair.open) {
			rest := s[len(pair.open):]
			if idx := strings.Index(rest, pair.close); idx >= 0 {
				return idx
			}
		}
	}
	return -1
}

// ---------------------------------------------------------------------------
// Test file detection
// ---------------------------------------------------------------------------

// testDirSegments are directory names that indicate test code.
var testDirSegments = []string{
	"/test/",
	"/tests/",
	"/testdata/",
	"/fixtures/",
	"/fixture/",
	"/__tests__/",
	"/spec/",
	"/__mocks__/",
	"/__fixtures__/",
	"/testing/",
	"/test_data/",
	"/src/test/",  // Maven/Gradle convention
	"/src/it/",    // Maven integration tests
	"/unittest/",  // Gitea / xorm convention (models/unittest/)
	"/testutil/",  // Go convention for test helpers
	"/testutils/", // Go convention for test helpers
	"/testhelper/",
	"/testhelpers/",
	"/integration/", // /integration/ test suites
	"/integrations/",
	"/e2e/",       // end-to-end tests
	"/scaletest/", // Coder convention: load/scale-testing tooling
	"/scaletests/",
	"/test_fixtures/", // ad-hoc fixture trees
	"/test-fixtures/",
}

// testFileSuffixes are filename suffixes that indicate test files.
var testFileSuffixes = []string{
	"_test.go",
	"_test.py",
	"_test.rb",
	"_test.rs",
	"_test.c",
	"_test.cpp",
	"_test.java",
	"_test.cs",
	".test.js",
	".test.jsx",
	".test.ts",
	".test.tsx",
	".test.mjs",
	".spec.js",
	".spec.jsx",
	".spec.ts",
	".spec.tsx",
	".spec.rb",
	"_spec.rb",
}

// javaTestSuffixes match Java/Kotlin conventional test class names.
var javaTestSuffixes = []string{
	"Test.java",
	"Tests.java",
	"IT.java", // integration tests
	"ITCase.java",
	"Spec.java",
	"Test.kt",
	"Tests.kt",
	"IT.kt",
}

// testFileNames are exact base filenames that indicate test/config files.
var testFileNames = []string{
	"conftest.py",
	"tests.py", // Django convention: single-file tests module
	"setup_test.go",
	"cypress.config.ts",
	"cypress.config.js",
	"playwright.config.ts",
	"playwright.config.js",
}

// vendoredJSLibPrefixes are filename prefixes for well-known third-party JS
// libraries that should be treated as generated/vendored code.
var vendoredJSLibPrefixes = []string{
	"jquery",
	"backbone",
	"underscore",
	"lodash",
	"moment",
	"angular.", // Angular 1.x vendored builds
	"react.",   // vendored React builds
	"vue.",     // vendored Vue builds
	"bootstrap",
	"d3.",
	"three.",
	"ace.",
	"codemirror",
	"highlight",
	"prism",
	"wysihtml",
	"ckeditor",
	"tinymce",
	"quill",
	"popper",
	"chart.",
	"raphael",
	"ember",
	"knockout",
	"mootools",
	"prototype.",
	"dojo",
	"ext-all",
	"handlebars",
	"mustache",
	"require.",
	"modernizr",
	"socket.io",
}

// vendoredDirPatterns are path substrings for directories containing
// third-party or educational/challenge code that is not production code.
var vendoredDirPatterns = []string{
	"/assets/private/",
	"/static/vendor/",
	"/third_party/",
	"/3rdparty/",
	"/external/",
	"/codefixes/", // intentionally vulnerable challenge snippets
	"/codefix/",
	"/snippets/challenge/",
	// Composer's generated autoloader runtime. The canonical layout is
	// vendor/composer/ (skipped via the /vendor/ generatedPathPatterns
	// entry), but per-component autoloaders land at
	// <component>/composer/composer/ — Nextcloud ships one under every
	// apps/<app>/composer/composer/ and under lib/composer/composer/. Every
	// file under this doubled segment is a Composer-generated artifact
	// (ClassLoader.php, InstalledVersions.php, autoload_*.php, installed.php,
	// platform_check.php), never the app's own code, so the whole directory
	// is third-party. The doubled segment is required (both slashes), so a
	// project's own /composer/ dir holding composer.json is not matched.
	"/composer/composer/",
}

// infraDirSegments are directory names that indicate infrastructure /
// scaffolding code (DB migrations, build tooling, code generators).
//
// These paths intentionally contain patterns that look unsafe to a generic
// scanner — DDL string-interpolation in migrations, exec-with-variable in
// build tools, dynamic code construction in generators — but are not part
// of the request-handling surface and operate on internal, trusted inputs.
var infraDirSegments = []string{
	"/migrations/",
	"/migration/",
	"/migrate/",
	"/db/migrate/", // Rails / Sequel convention
	"/schema/migrations/",
	"/cmd/tools/",
	"/build/tools/",
	"/tools/", // build-time tooling (linters, codegen runners)
	"/generator/",
	"/generators/",
	"/codegen/",
	"/script/",
	"/scripts/",
	"/devtest/", // Gitea convention: developer-only test endpoints
	"/devtests/",
	"/devtools/",
	// ember-cli-mirage: a client-side MOCK SERVER that only runs in dev/test
	// (route handlers backed by an in-memory fake ORM). Its `request.params`
	// -> `schema.find()` handlers read as NoSQL/SQL injection to a generic
	// scanner but never touch a production datastore. Path-segment match so it
	// only fires on a real `mirage/` directory, not a substring.
	"/mirage/",
	// Python infrastructure / vendored environments.
	// These contain library, build, or dev-only code that intentionally
	// uses patterns that look unsafe (eval in stubs, subprocess in
	// setup hooks, dynamic imports in migrations) but aren't part of
	// the request-handling surface.
	"/__pycache__/",   // Python bytecode cache
	"/.tox/",          // tox virtual envs (test matrices)
	"/.nox/",          // nox virtual envs
	"/venv/",          // conventional virtualenv directory
	"/.venv/",         // PEP-405 / poetry convention
	"/site-packages/", // installed third-party Python packages
	"/dist-packages/", // Debian-style installed Python packages
	"/.eggs/",         // setuptools egg cache
	"/eggs/",          // setuptools egg cache (older layout)
	"/.pytest_cache/", // pytest cache
	"/.mypy_cache/",   // mypy cache
	"/.ruff_cache/",   // ruff cache
	"/docs/",          // documentation trees (Sphinx, MkDocs, etc.)
	// Benchmarking harness paths. These intentionally exec child
	// processes, eval arbitrary code, parse untrusted-looking input,
	// etc. — the whole point of a benchmark is to drive the system
	// under test with a workload, which often looks like an attacker
	// to a SAST. node.js, V8, fastlane, etc. all have a benchmark/
	// directory with these patterns. Surfaced via scan_harness on
	// nodejs/node — 5/5 BATOU-JSAST-004 hits at CRITICAL were in
	// benchmark/_http-benchmarkers.js etc.
	"/benchmark/",
	"/benchmarks/",
	"/bench/",
	"/perf/",
	"/perf_test/",
	"/performance/",
	// Code-generation / language-server deps trees. These ship
	// stub or fixture code that often contains unsafe-looking
	// patterns for parser testing.
	"/deps/v8/test/",
	"/test-cases/",
	"/test_cases/",
	// Documentation example trees ship code snippets that intentionally
	// demonstrate API usage — they're sample fixtures, not the
	// project's request surface. FastAPI's /docs_src/ tree is the
	// canonical example. scan_harness sample: 47.5 hits/repo of
	// BATOU-FW-FASTAPI-008 on FastAPI's own docs_src/.
	"/docs_src/",
	"/example/",
	"/examples/",
	"/sample/",
	"/samples/",
	"/demo/",
	"/demos/",
}

// infraFileSuffixes are filename suffixes that indicate generated or
// generator code (the file that emits generated code, not the output).
var infraFileSuffixes = []string{
	"_gen.go", // Go generator output
	".gen.go",
	".pb.go", // protobuf generated
	"_generated.go",
	"_generated.ts",
	"_generated.js",
}

// infraFileNames are exact base filenames that indicate generator scripts
// (the file is itself a code generator, run via `go generate` / `make gen`)
// OR test/dev-environment setup files that ship in production packages
// but only execute under test/dev conditions.
var infraFileNames = []string{
	"generate.go",
	"gen.go",
	"main_generate.go",
	"testenv.go", // Gitea / Go convention: test-environment setup
	"test_env.go",
	"devenv.go",
	"dev_env.go",
	// Python build / packaging / management scripts. These run at install
	// or admin time, not in response to user requests, so dynamic-exec or
	// path-construction patterns inside them aren't request-surface bugs.
	// (conftest.py is covered by testFileNames; not duplicated here.)
	"setup.py",
	"setup.cfg",
	"manage.py", // Django entry point (runs subprocesses, exec'd from CLI)
}

// testPathKeywords are case-insensitive substrings that indicate test-like files.
var testPathKeywords = []string{
	"mock",
	"fake",
	"stub",
	"example",
}

// IsTestFile returns true if the file path looks like a test, fixture, mock,
// or example file.
func IsTestFile(filePath string) bool {
	norm := filepath.ToSlash(filePath)
	// Prepend "/" so patterns like "/test/" also match relative paths
	// that start with "test/".
	lower := strings.ToLower("/" + norm)

	// Directory segments.
	for _, seg := range testDirSegments {
		if strings.Contains(lower, seg) {
			return true
		}
	}

	// File suffixes.
	for _, suf := range testFileSuffixes {
		if strings.HasSuffix(lower, suf) {
			return true
		}
	}

	// Java/Kotlin conventional test class suffixes (case-sensitive).
	base := filepath.Base(filePath)
	for _, suf := range javaTestSuffixes {
		if strings.HasSuffix(base, suf) {
			return true
		}
	}

	// Exact base filenames.
	baseLower := strings.ToLower(base)
	for _, name := range testFileNames {
		if baseLower == name {
			return true
		}
	}

	// Test file name patterns: test_*.py
	if strings.HasPrefix(baseLower, "test_") && strings.HasSuffix(baseLower, ".py") {
		return true
	}

	// CI test-runner shell scripts that live at the repo root (so the
	// /tests/ and /benchmarks/ directory segments don't catch them).
	// Nextcloud / ownCloud ship autotest.sh, autotest-external.sh,
	// autotest-checkers.sh at the project root — these drive the test suite
	// (spin up DBs, exec phpunit, etc.) and intentionally contain shell
	// patterns that read as command-injection to a SAST but operate on
	// internal, trusted inputs. The "autotest" prefix + .sh suffix is a
	// narrow, well-known convention.
	if strings.HasPrefix(baseLower, "autotest") && strings.HasSuffix(baseLower, ".sh") {
		return true
	}

	// Keywords in the path.
	for _, kw := range testPathKeywords {
		if strings.Contains(lower, kw) {
			return true
		}
	}

	return false
}

// IsInfraFile returns true if the file looks like infrastructure /
// scaffolding code (DB migrations, build-time tooling, code generators).
//
// These paths run with internal, trusted inputs and intentionally contain
// patterns that read as unsafe in user-facing code — for example, DDL
// string-interpolation in migrations or exec-with-variable in build tools.
// Treat findings here like test-file findings: keep them as hints, not blocks.
func IsInfraFile(filePath string) bool {
	norm := filepath.ToSlash(filePath)
	lower := strings.ToLower("/" + norm)

	for _, seg := range infraDirSegments {
		if strings.Contains(lower, seg) {
			return true
		}
	}

	for _, suf := range infraFileSuffixes {
		if strings.HasSuffix(lower, suf) {
			return true
		}
	}

	baseLower := strings.ToLower(filepath.Base(filePath))
	for _, name := range infraFileNames {
		if baseLower == name {
			return true
		}
	}

	return false
}

// IsInfraOrTestPath returns true if a path looks like test code, fixtures,
// build tooling, code generators, scale-testing harnesses, or any other
// non-production "support" path. It is the union of IsTestFile and
// IsInfraFile and exists as a single helper because both kinds of paths
// get the same confidence-cap treatment in the scanner: findings on them
// drop to 0.3 so they don't reach the 0.7 block threshold.
func IsInfraOrTestPath(filePath string) bool {
	return IsTestFile(filePath) || IsInfraFile(filePath)
}

// ---------------------------------------------------------------------------
// Vendored / third-party library detection
// ---------------------------------------------------------------------------

// IsVendoredLibrary returns true if the file looks like a known third-party
// JavaScript library or lives in a vendored/third-party directory.
// These files produce noise because they contain patterns (eval, innerHTML, etc.)
// that are intentional library internals, not application vulnerabilities.
func IsVendoredLibrary(filePath string) bool {
	norm := "/" + filepath.ToSlash(filePath)
	lower := strings.ToLower(norm)

	// Check vendored directory patterns.
	for _, pat := range vendoredDirPatterns {
		if strings.Contains(lower, pat) {
			return true
		}
	}

	// Check known JS library filenames (only for .js files).
	ext := strings.ToLower(filepath.Ext(filePath))
	if ext == ".js" {
		baseLower := strings.ToLower(filepath.Base(filePath))
		for _, prefix := range vendoredJSLibPrefixes {
			if strings.HasPrefix(baseLower, prefix) {
				return true
			}
		}
	}

	return false
}
