// Java Spring/MyBatis cross-file interprocedural support.
//
// This file closes the two "hard stops" that broke the
// controller → service-interface → MyBatis-mapper taint chain on
// macrozheng/mall-style apps (see /tmp/coverage/java-interproc-design.md):
//
//  1. Interface dispatch. A Spring controller holds an @Autowired /
//     @Resource / @Inject field whose declared type is a *service or
//     mapper interface*, and calls `fooService.bar(...)` /
//     `userMapper.listBySort(...)`. The base javaResolver dropped those
//     calls (field receiver, no type inference) so no Calls/CalledBy edge
//     was ever created and the transitive-caller walk had nothing to
//     traverse. We now capture per-file field types + `implements`
//     clauses + the @Mapper/@Service/@Repository class annotations during
//     ExtractScope, build a project-wide interface→impl ImplIndex during
//     the cross-file pass, and resolve a field-receiver call to either the
//     concrete @Service impl method (single-impl-only, heuristic) or — for
//     a @Mapper interface, whose impl is generated by MyBatis at runtime —
//     to the mapper *interface method node itself*.
//
//  2. MyBatis annotation sinks. A @Mapper interface method carrying an
//     @Select / @Update / @Delete / @Insert / @SelectProvider / ... whose
//     SQL contains `${...}` string substitution is a SQL-injection sink
//     (CWE-89). `#{...}` is parameterised (prepared-statement binding) and
//     is safe — it MUST NOT fire. We synthesise a SnkSQLQuery SinkRef onto
//     such a method's TaintSignature so the normal interproc walk reaches
//     it from the controller's tainted @RequestParam.
//
// Phase 1 (this file) is Java-source-only: interface dispatch + annotation
// `${}` sinks. The XML mapper-file path (`<select id="...">... ${} ...`)
// is DESIGN-noted (see java-interproc-design.md §2b) and intentionally not
// implemented here — it is the larger, higher-FP-risk lift and warrants
// its own benchmark gate.
package graph

import (
	"regexp"
	"strings"

	tsast "github.com/turenlabs/batou-core/ast"
	"github.com/turenlabs/batou-core/taint"
	"github.com/turenlabs/batou-rules/rules"
)

// Aux key prefixes used by the Java resolver to stash the field/impl/
// annotation maps captured in ExtractScope. They share the single
// FileScope.Aux string map; prefixes keep the namespaces disjoint.
const (
	// javaAuxFieldPrefix + fieldName → declared (short) type name.
	// e.g. "jfield:userService" → "UserService".
	javaAuxFieldPrefix = "jfield:"
	// javaAuxMapperIfacePrefix + interfaceShortName → "1" when the
	// interface (or the class) carries an @Mapper annotation. Mapper
	// interfaces resolve to their own method node (the impl is generated
	// by MyBatis at runtime), not to a Java impl class.
	javaAuxMapperPrefix = "jmapper:"
	// javaAuxImplementsPrefix + className → comma-joined interface short
	// names the class implements. Used to build the project-wide
	// ImplIndex. e.g. "jimpl:UserServiceImpl" → "UserService".
	javaAuxImplementsPrefix = "jimpl:"
	// javaAuxBeanPrefix + className → "1" when the class carries a
	// Spring bean annotation (@Service/@Component/@Repository/@Mapper).
	// Used to prefer a bean-annotated impl when selecting among
	// candidates.
	javaAuxBeanPrefix = "jbean:"
)

// javaDIAnnotations are the field-injection annotations Spring / JSR-330
// use. A field carrying one of these is dependency-injected and its
// declared (interface) type is what the call dispatches against.
var javaDIAnnotations = map[string]bool{
	"Autowired": true,
	"Resource":  true,
	"Inject":    true,
}

// javaBeanClassAnnotations are the class-level Spring stereotype
// annotations marking an injectable bean. A class carrying one of these
// is preferred when selecting among multiple impl candidates.
var javaBeanClassAnnotations = map[string]bool{
	"Service":    true,
	"Component":  true,
	"Repository": true,
	"Mapper":     true,
}

// reMyBatisDollarInterp matches a MyBatis `${...}` substitution token.
// `#{...}` (prepared-statement binding) is deliberately NOT matched: the
// negative lookbehind RE2 can't express is unnecessary because we anchor
// on `${` — `#{` simply doesn't contain the `$` so it never matches.
var reMyBatisDollarInterp = regexp.MustCompile(`\$\{[^}]*\}`)

// reMyBatisAnnotation matches the MyBatis SQL-statement annotations that
// can carry inline SQL. Provider variants (@SelectProvider, …) point at a
// method that builds the SQL string dynamically — also injectable — so we
// include them.
var reMyBatisAnnotation = regexp.MustCompile(
	`@(?:Select|Update|Delete|Insert|SelectProvider|UpdateProvider|DeleteProvider|InsertProvider)\b`)

// collectJavaClassMetadata walks a parsed Java file and records, into the
// scope's Aux map, the data the interface-dispatch resolver needs:
//
//   - field name → declared type short name (DI fields only)
//   - class name → implemented-interface short names (jimpl:)
//   - interface/class name → @Mapper flag (jmapper:)
//   - class name → Spring-bean flag (jbean:)
//
// Reuses the same tree already parsed by ExtractScope — no extra I/O.
func collectJavaClassMetadata(root *tsast.Node, aux map[string]string) {
	if root == nil || aux == nil {
		return
	}
	var walk func(n *tsast.Node)
	walk = func(n *tsast.Node) {
		if n == nil {
			return
		}
		for _, child := range n.NamedChildren() {
			switch child.Type() {
			case "class_declaration", "interface_declaration",
				"record_declaration", "enum_declaration":
				className := nodeFieldText(child, "name")
				if className != "" {
					recordJavaTypeMetadata(child, className, aux)
				}
				if body := child.ChildByFieldName("body"); body != nil {
					// Capture DI fields declared directly in this class
					// body, then recurse for nested types.
					collectJavaFieldTypes(body, aux)
					walk(body)
				}
			default:
				walk(child)
			}
		}
	}
	walk(root)
}

// recordJavaTypeMetadata records the @Mapper / bean-stereotype flags and
// the `implements` interface list for a single class/interface node.
func recordJavaTypeMetadata(typeNode *tsast.Node, className string, aux map[string]string) {
	isMapper := false
	isBean := false
	if mods := firstChildOfType(typeNode, "modifiers"); mods != nil {
		for _, ann := range mods.NamedChildren() {
			name := annotationName(ann)
			if name == "" {
				continue
			}
			if name == "Mapper" {
				isMapper = true
			}
			if javaBeanClassAnnotations[name] {
				isBean = true
			}
		}
	}
	if isMapper {
		aux[javaAuxMapperPrefix+className] = "1"
	}
	if isBean {
		aux[javaAuxBeanPrefix+className] = "1"
	}
	// `class Foo implements Bar, Baz` — the super_interfaces child holds
	// a type_list of the implemented interface names.
	if ifaces := collectImplementedInterfaces(typeNode); len(ifaces) > 0 {
		aux[javaAuxImplementsPrefix+className] = strings.Join(ifaces, ",")
	}
}

// collectImplementedInterfaces returns the short names of every interface
// in a class's `implements` clause (the super_interfaces → type_list).
func collectImplementedInterfaces(typeNode *tsast.Node) []string {
	var out []string
	for _, c := range typeNode.NamedChildren() {
		if c.Type() != "super_interfaces" {
			continue
		}
		for _, tl := range c.NamedChildren() {
			if tl.Type() != "type_list" {
				continue
			}
			for _, t := range tl.NamedChildren() {
				if name := javaTypeShortName(t); name != "" {
					out = append(out, name)
				}
			}
		}
	}
	return out
}

// collectJavaFieldTypes records DI-injected field declarations in a class
// body: field name → declared (short) type name. Only fields carrying an
// @Autowired / @Resource / @Inject annotation are recorded, since those
// are the dependency-injected receivers whose static type is an interface
// that interface dispatch needs to resolve against.
func collectJavaFieldTypes(body *tsast.Node, aux map[string]string) {
	for _, child := range body.NamedChildren() {
		if child.Type() != "field_declaration" {
			continue
		}
		if !javaFieldIsDIInjected(child) {
			continue
		}
		typeNode := child.ChildByFieldName("type")
		if typeNode == nil {
			continue
		}
		typeName := javaTypeShortName(typeNode)
		if typeName == "" {
			continue
		}
		for _, c := range child.NamedChildren() {
			if c.Type() != "variable_declarator" {
				continue
			}
			nameNode := c.ChildByFieldName("name")
			if nameNode == nil {
				continue
			}
			fieldName := strings.TrimSpace(nameNode.Text())
			if fieldName != "" {
				aux[javaAuxFieldPrefix+fieldName] = typeName
			}
		}
	}
}

// javaFieldIsDIInjected reports whether a field_declaration carries an
// @Autowired / @Resource / @Inject annotation in its modifiers.
func javaFieldIsDIInjected(field *tsast.Node) bool {
	mods := firstChildOfType(field, "modifiers")
	if mods == nil {
		return false
	}
	for _, ann := range mods.NamedChildren() {
		if javaDIAnnotations[annotationName(ann)] {
			return true
		}
	}
	return false
}

// annotationName returns the short identifier of an annotation node
// (`marker_annotation` for @Autowired, `annotation` for @Select("...")).
// Returns "" for non-annotation nodes.
func annotationName(n *tsast.Node) string {
	if n == nil {
		return ""
	}
	if n.Type() != "annotation" && n.Type() != "marker_annotation" {
		return ""
	}
	if nameNode := n.ChildByFieldName("name"); nameNode != nil {
		// Annotation name may be qualified
		// (@org.springframework...Autowired); take the trailing segment.
		return javaShortName(strings.TrimSpace(nameNode.Text()))
	}
	return ""
}

// javaTypeShortName extracts the short type name from a type node,
// stripping generics and qualifiers: `List<User>` → "List",
// `com.foo.Bar` → "Bar".
func javaTypeShortName(n *tsast.Node) string {
	if n == nil {
		return ""
	}
	switch n.Type() {
	case "type_identifier", "identifier":
		return strings.TrimSpace(n.Text())
	case "generic_type":
		// First named child is the base type_identifier / scoped name.
		for _, c := range n.NamedChildren() {
			if name := javaTypeShortName(c); name != "" {
				return name
			}
		}
	case "scoped_type_identifier", "scoped_identifier":
		return javaShortName(strings.TrimSpace(n.Text()))
	}
	// Fallback: take the raw text, strip generics/qualifier.
	return javaShortName(strings.TrimSpace(n.Text()))
}

// javaShortName returns the trailing dotted segment of a (possibly
// qualified, possibly generic) type name. `com.foo.Bar<X>` → "Bar".
func javaShortName(s string) string {
	if i := strings.IndexAny(s, "<["); i >= 0 {
		s = s[:i]
	}
	s = strings.TrimSpace(s)
	if dot := strings.LastIndexByte(s, '.'); dot >= 0 {
		s = s[dot+1:]
	}
	return strings.TrimSpace(s)
}

// firstChildOfType returns the first direct named child of n with the
// given type, or nil.
func firstChildOfType(n *tsast.Node, typ string) *tsast.Node {
	if n == nil {
		return nil
	}
	for _, c := range n.NamedChildren() {
		if c.Type() == typ {
			return c
		}
	}
	return nil
}

// --- ImplIndex: project-wide interface → impl class file index ---------------

// ImplIndex maps an interface short name to the absolute file paths of the
// classes that `implements` it. Built during the cross-file resolution
// pass from every file's `jimpl:` Aux entries. Keyed by short name (Java
// has no global namespace; the resolver already keys imports on file
// paths) — collisions across packages are rare in the single-module
// Spring apps this targets and are tolerated (we still prefer a
// bean-annotated impl among candidates).
type ImplIndex struct {
	// byInterface maps interface short name → impl file records.
	byInterface map[string][]implRecord
}

type implRecord struct {
	className string
	filePath  string
	isBean    bool
}

// newImplIndex returns an empty ImplIndex.
func newImplIndex() *ImplIndex {
	return &ImplIndex{byInterface: map[string][]implRecord{}}
}

// add records that className (declared in filePath, isBean) implements
// each of ifaces.
func (ii *ImplIndex) add(className, filePath string, isBean bool, ifaces []string) {
	if ii == nil {
		return
	}
	for _, iface := range ifaces {
		iface = strings.TrimSpace(iface)
		if iface == "" {
			continue
		}
		ii.byInterface[iface] = append(ii.byInterface[iface], implRecord{
			className: className,
			filePath:  filePath,
			isBean:    isBean,
		})
	}
}

// lookup returns the single best impl for an interface short name, and
// whether a unique choice was made. v1 is single-impl-only (per the design
// doc): when exactly one impl exists we return it; when several exist we
// prefer a unique bean-annotated one, else report ok=false so the caller
// leaves the call unresolved rather than guessing.
func (ii *ImplIndex) lookup(iface string) (implRecord, bool) {
	if ii == nil {
		return implRecord{}, false
	}
	recs := ii.byInterface[iface]
	switch len(recs) {
	case 0:
		return implRecord{}, false
	case 1:
		return recs[0], true
	}
	// Multiple impls: prefer a unique bean-annotated candidate.
	var beans []implRecord
	for _, r := range recs {
		if r.isBean {
			beans = append(beans, r)
		}
	}
	if len(beans) == 1 {
		return beans[0], true
	}
	return implRecord{}, false
}

// buildJavaImplIndex constructs the project-wide ImplIndex from every
// Java FileScope's `jimpl:` / `jbean:` Aux entries. Returns nil when no
// Java implements-clauses were captured (so callers can cheaply skip the
// interface-dispatch path on non-Java / non-Spring projects).
func buildJavaImplIndex(scopes map[string]FileScope) *ImplIndex {
	idx := newImplIndex()
	any := false
	for path, scope := range scopes {
		if len(scope.Aux) == 0 {
			continue
		}
		for k, v := range scope.Aux {
			if !strings.HasPrefix(k, javaAuxImplementsPrefix) {
				continue
			}
			className := strings.TrimPrefix(k, javaAuxImplementsPrefix)
			ifaces := strings.Split(v, ",")
			isBean := scope.Aux[javaAuxBeanPrefix+className] == "1"
			idx.add(className, path, isBean, ifaces)
			any = true
		}
	}
	if !any {
		return nil
	}
	return idx
}

// --- MyBatis annotation sink detection ---------------------------------------

// javaBodyHasMyBatisDollarSink reports whether the given function-body
// text (the method node's full source text, which in tree-sitter includes
// the leading @Select/@Update/... annotation) contains a MyBatis SQL
// annotation whose SQL carries a `${...}` substitution. `#{...}` alone is
// safe and returns false.
func javaBodyHasMyBatisDollarSink(body string) bool {
	if !reMyBatisAnnotation.MatchString(body) {
		return false
	}
	return reMyBatisDollarInterp.MatchString(body)
}

// mybatisDollarParamNames returns the set of identifier names referenced
// inside `${...}` tokens in body — these name the injectable bind
// variables (e.g. `${sort}` → "sort"). Used to map the sink back to the
// mapper method's parameter index so the cross-file walk can pair the
// controller's tainted argument with this sink positionally.
func mybatisDollarParamNames(body string) []string {
	matches := reMyBatisDollarInterp.FindAllString(body, -1)
	var out []string
	for _, m := range matches {
		// Strip the `${` and `}` then take the leading identifier (handle
		// `${order.column}` → "order").
		inner := strings.TrimSuffix(strings.TrimPrefix(m, "${"), "}")
		inner = strings.TrimSpace(inner)
		if inner == "" {
			continue
		}
		if dot := strings.IndexByte(inner, '.'); dot >= 0 {
			inner = inner[:dot]
		}
		// Keep only a leading identifier-ish token.
		inner = leadingIdent(inner)
		if inner != "" {
			out = append(out, inner)
		}
	}
	return out
}

// leadingIdent returns the leading [A-Za-z_][A-Za-z0-9_]* run of s.
func leadingIdent(s string) string {
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c == '_' || (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
			(i > 0 && c >= '0' && c <= '9') {
			continue
		}
		return s[:i]
	}
	return s
}

// maybeAppendMyBatisSink inspects a Java function node's body and, when it
// is a MyBatis mapper method carrying a `${...}` SQL annotation, appends a
// synthetic SnkSQLQuery SinkRef (CWE-89) to sig. The sink's ArgFromParam
// is set to the index of the mapper-method parameter whose name appears in
// a `${...}` token (so the controller→mapper positional flow match works),
// or -1 when no parameter name matches (then the interproc walk's -1
// wildcard fallback applies — valid because mapper methods have no
// SourceParams).
//
// Idempotent: it will not append a second mapper sink if one is already
// present (so re-running signature computation doesn't duplicate it).
func maybeAppendMyBatisSink(node *FuncNode, body string, sig *TaintSignature) {
	if node == nil || node.Language != rules.LangJava {
		return
	}
	if !javaBodyHasMyBatisDollarSink(body) {
		return
	}
	for _, s := range sig.SinkCalls {
		if s.MethodName == javaMyBatisSinkMethod {
			return // already recorded
		}
	}
	argFrom := -1
	names := mybatisDollarParamNames(body)
	if len(names) > 0 {
		if idx := javaParamIndexByName(sig, names); idx >= 0 {
			argFrom = idx
		}
	}
	sig.SinkCalls = append(sig.SinkCalls, SinkRef{
		SinkCategory: taint.SnkSQLQuery,
		MethodName:   javaMyBatisSinkMethod,
		Line:         node.StartLine,
		ArgFromParam: argFrom,
	})
	// A node that is purely a mapper sink is no longer "pure".
	sig.IsPure = false
}

// javaMyBatisSinkMethod is the synthetic MethodName carried by the
// mapper-annotation SQL sink. Stable string so dedup / idempotency checks
// can recognise it.
const javaMyBatisSinkMethod = "MyBatis @Select ${} (SQL injection)"

// javaParamIndexByName returns the index of the first signature parameter
// whose name matches any of the given dollar-token names, or -1. The match
// also accepts the parameter's @Param("x") binding name when the source
// param was recorded with that name; since the typed extractor records the
// Java identifier (not the @Param value), we match the identifier here.
func javaParamIndexByName(sig *TaintSignature, names []string) int {
	if sig == nil || len(sig.Params) == 0 {
		return -1
	}
	want := map[string]bool{}
	for _, n := range names {
		want[n] = true
	}
	for _, p := range sig.Params {
		if p.Name != "" && want[p.Name] {
			return p.Index
		}
	}
	return -1
}
